apiVersion: v1
kind: Service
metadata:
  name: archery-tracker-fe-only
  namespace: archery-tracker-fe-only
  labels:
    app: archery-tracker-fe-only
spec:
  selector:
    app: archery-tracker-fe-only
  ports:
    - port: 80
      targetPort: 80
      name: http
