apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-ingress
  namespace: argocd
spec:
  project: default
  source:
    chart: cloudflare-tunnel-ingress-controller
    repoURL: https://helm.strrl.dev
    targetRevision: 0.0.22
    helm:
      values: |
        cloudflare:
          tunnelName: "k3s-jeammm"
          secretName: "cloudflare-creds"
        controller:
          env:
            - name: CLOUDFLARE_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflare-creds
                  key: CLOUDFLARE_API_TOKEN
            - name: CLOUDFLARE_ACCOUNT_ID
              valueFrom:
                secretKeyRef:
                  name: cloudflare-creds
                  key: CLOUDFLARE_ACCOUNT_ID
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflare-tunnel-ingress-controller
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    createNamespace: true