apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-tunnel
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Jeammm/infra-manifest.git
    path: cluster-config/cloudflare-tunnel
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflare-tunnel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
